import { StyleSheet } from 'react-native';

import { colors } from '@/esopay/theme/colors';
import { spacing } from '@/esopay/theme/spacing';
import { fonts } from '@/esopay/theme/typography';

export const paymentModalStyles = StyleSheet.create({
  sheetBg: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: colors.goldBorder,
  },
  handle: {
    backgroundColor: colors.goldDim,
    width: 44,
  },
  content: {
    paddingHorizontal: spacing.screen,
    paddingBottom: spacing.xxxl,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.lg,
    gap: spacing.md,
  },
  headerCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    fontFamily: fonts.uiMedium,
    fontSize: 10,
    letterSpacing: 1.5,
    color: colors.gold,
    textTransform: 'uppercase',
  },
  title: {
    fontFamily: fonts.display,
    fontSize: 26,
    color: colors.white,
  },
  fieldLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 12,
    color: colors.muted,
    marginBottom: spacing.sm,
  },
  fieldGap: {
    marginTop: spacing.lg,
  },
  input: {
    backgroundColor: colors.surface2,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.goldBorder,
    paddingHorizontal: spacing.lg,
    paddingVertical: 14,
    fontFamily: fonts.ui,
    fontSize: 16,
    color: colors.white,
  },
  lookupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  customerName: {
    marginTop: spacing.sm,
    fontFamily: fonts.uiMedium,
    fontSize: 14,
    color: colors.gold,
  },
  validationError: {
    marginTop: spacing.sm,
    fontFamily: fonts.ui,
    fontSize: 13,
    color: colors.danger,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface2,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.goldBorder,
    paddingHorizontal: spacing.lg,
  },
  nairaPrefix: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.gold,
    marginRight: spacing.sm,
  },
  amountInput: {
    flex: 1,
    paddingVertical: 14,
    fontFamily: fonts.display,
    fontSize: 28,
    color: colors.white,
  },
  walletHint: {
    marginTop: spacing.sm,
    fontFamily: fonts.ui,
    fontSize: 13,
    color: colors.muted,
  },
  walletHintWarn: {
    color: colors.warning,
  },
  walletWarn: {
    marginTop: spacing.sm,
    fontFamily: fonts.ui,
    fontSize: 13,
    lineHeight: 18,
    color: colors.warning,
  },
  addFundsBtn: {
    marginTop: spacing.md,
  },
  toggleRow: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleLabel: {
    fontFamily: fonts.ui,
    fontSize: 14,
    color: colors.white,
  },
  rbacHint: {
    marginTop: spacing.md,
    fontFamily: fonts.ui,
    fontSize: 13,
    color: colors.warning,
  },
  payBtn: {
    marginTop: spacing.xl,
  },
  disclaimer: {
    marginTop: spacing.md,
    fontFamily: fonts.ui,
    fontSize: 12,
    lineHeight: 18,
    color: colors.muted,
    textAlign: 'center',
  },
  successBlock: {
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.xxl,
  },
  successTitle: {
    fontFamily: fonts.display,
    fontSize: 28,
    color: colors.white,
    textAlign: 'center',
  },
  fulfillmentMessage: {
    fontFamily: fonts.ui,
    fontSize: 15,
    lineHeight: 23,
    color: colors.white,
    textAlign: 'center',
    paddingHorizontal: 8,
    marginTop: 4,
  },
  successAmount: {
    fontFamily: fonts.display,
    fontSize: 36,
    color: colors.gold,
  },
  refText: {
    fontFamily: fonts.ui,
    fontSize: 13,
    color: colors.muted,
  },
  statusPill: {
    fontFamily: fonts.uiMedium,
    fontSize: 12,
    color: colors.gold,
    textTransform: 'capitalize',
  },
  tokenBox: {
    width: '100%',
    backgroundColor: colors.surface2,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.goldBorder,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  tokenLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 11,
    letterSpacing: 1,
    color: colors.gold,
    textTransform: 'uppercase',
  },
  tokenValue: {
    fontFamily: fonts.ui,
    fontSize: 16,
    color: colors.white,
    lineHeight: 24,
  },
  receiptActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    width: '100%',
  },
  secondaryBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.goldBorder,
    backgroundColor: colors.surface2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryBtnText: {
    fontFamily: fonts.uiMedium,
    fontSize: 14,
    color: colors.gold,
  },
  processingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  processingText: {
    fontFamily: fonts.ui,
    fontSize: 14,
    color: colors.muted,
  },
  backLink: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  backLinkText: {
    fontFamily: fonts.uiMedium,
    fontSize: 14,
    color: colors.gold,
  },
  bundleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  bundleChip: {
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.goldBorder,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    gap: 2,
  },
  bundleChipActive: {
    borderColor: colors.gold,
    backgroundColor: colors.goldGlow,
  },
  bundleLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 13,
    color: colors.white,
  },
  bundleLabelActive: {
    color: colors.gold,
  },
  bundleSub: {
    fontFamily: fonts.ui,
    fontSize: 10,
    color: colors.muted,
  },
});
