/** @type {import('tailwindcss').Config} */
const GOLD = '#C9A84C';

module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'paybills-bg': '#080808',
        'paybills-surface': '#111111',
        'paybills-input': '#161616',
        'paybills-border': '#1E1E1E',
        'paybills-muted': '#666666',
        'paybills-gold-gray': '#7A7168',
        'stripe-purple': '#635BFF',
        'stripe-teal': '#00C896',
        'stripe-gold': GOLD,
        'stripe-bg': '#F6F9FC',
        'stripe-navy': '#0A2540',
        'stripe-border': '#e6e6f0',
        obsidian: '#000000',
        charcoal: {
          from: '#0D0D10',
          to: '#141419',
        },
        'electric-teal': '#00E5FF',
        'command-gold': GOLD,
        'eso-base': '#0b0f19',
        'eso-surface': '#111827',
        'eso-elevated': '#1a2234',
        'eso-border': '#1e293b',
        'eso-border2': '#27374d',
        'eso-primary': '#f1f5f9',
        'eso-secondary': '#94a3b8',
        'eso-tertiary': '#475569',
        'eso-accent': '#60a5fa',
        'pay-mint': '#00c896',
        'pay-dark': '#040d0a',
        'pay-surface': '#0a1f18',
        'pay-elevated': '#0f2d22',
        'pay-muted': '#3d6b57',
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        regular: ['Inter_400Regular'],
        medium: ['Inter_500Medium'],
        semibold: ['Inter_600SemiBold'],
        bold: ['Inter_700Bold'],
        mono: ['Inter_400Regular'],
        serif: ['Inter_600SemiBold'],
        display: ['Inter_600SemiBold'],
        // Legacy class names map to Inter weights
        sora: ['Inter_400Regular'],
        'sora-medium': ['Inter_500Medium'],
        'sora-semibold': ['Inter_600SemiBold'],
        'sora-bold': ['Inter_700Bold'],
        'sora-extrabold': ['Inter_700Bold'],
        jakarta: ['Inter_400Regular'],
        'jakarta-medium': ['Inter_500Medium'],
        'jakarta-semibold': ['Inter_600SemiBold'],
        'jakarta-bold': ['Inter_700Bold'],
        'jakarta-extrabold': ['Inter_700Bold'],
      },
      fontSize: {
        label: '11px',
        badge: '12px',
        body: '13px',
        value: '15px',
        title: '18px',
        hero: '28px',
      },
      borderRadius: {
        badge: '4px',
        button: '6px',
        card: '8px',
        sheet: '12px',
      },
    },
  },
  plugins: [],
};
