import { StyleSheet } from 'react-native';
import {
  ESO_PAY_TEXT_PRIMARY,
  ESO_PAY_TEXT_SECONDARY,
  HOME_CARD_BORDER,
} from '@/esopay/theme/brandColors';
import { fonts } from '@/esopay/theme/typography';

/**
 * Quiet-luxury chrome for Electricity / Airtime / Data.
 * International fintech dialect — depth, type, space — not neon or clutter.
 */
export const utilityPayChrome = StyleSheet.create({
  screenPad: {
    paddingHorizontal: 20,
    paddingTop: 10,
    gap: 16,
  },
  surface: {
    borderRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.045)',
    overflow: 'hidden',
  },
  surfacePad: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 22,
    gap: 18,
  },
  sectionTitle: {
    fontFamily: fonts.uiMedium,
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.48)',
    includeFontPadding: false,
  },
  fieldLabel: {
    fontFamily: fonts.ui,
    fontSize: 12,
    letterSpacing: 0.2,
    color: 'rgba(255,255,255,0.4)',
    includeFontPadding: false,
  },
  link: {
    fontFamily: fonts.uiMedium,
    fontSize: 13,
    letterSpacing: -0.1,
    color: 'rgba(255,255,255,0.9)',
    includeFontPadding: false,
  },
  tile: {
    width: '31.2%',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.032)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  tileActive: {
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1.5,
    backgroundColor: 'rgba(255,255,255,0.11)',
    shadowColor: '#FFFFFF',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  tileCheck: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 22,
    height: 22,
    borderTopLeftRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountValue: {
    fontFamily: fonts.uiBold,
    fontSize: 18,
    letterSpacing: -0.55,
    color: ESO_PAY_TEXT_PRIMARY,
    includeFontPadding: false,
    fontVariant: ['tabular-nums'],
  },
  amountSub: {
    fontFamily: fonts.ui,
    fontSize: 10,
    letterSpacing: 0.2,
    color: 'rgba(255,255,255,0.32)',
    includeFontPadding: false,
    marginTop: 4,
  },
  inputShell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(0,0,0,0.32)',
    paddingHorizontal: 16,
  },
  payPill: {
    minWidth: 108,
    height: 56,
    borderRadius: 28,
    paddingHorizontal: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#FFFFFF',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  payPillDisabled: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.10)',
    shadowOpacity: 0,
    elevation: 0,
  },
  payPillText: {
    fontFamily: fonts.uiBold,
    fontSize: 16,
    letterSpacing: -0.2,
    color: '#0A0A0A',
    includeFontPadding: false,
  },
  payPillTextDisabled: {
    color: 'rgba(255,255,255,0.28)',
  },
  payWide: {
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#FFFFFF',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  error: {
    fontFamily: fonts.ui,
    fontSize: 13,
    color: '#E05252',
    includeFontPadding: false,
  },
  sheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  sheet: {
    maxHeight: '74%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#0C0C0C',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.10)',
    paddingBottom: 32,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.16)',
    marginTop: 12,
    marginBottom: 6,
  },
  secondary: {
    color: ESO_PAY_TEXT_SECONDARY,
  },
  border: {
    borderColor: HOME_CARD_BORDER,
  },
  heroShell: {
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
});
